### ISSUE TITLE
ListEditor_demo.py crashes with wx 3.0 as backend

### ISSUE THREAD

**Issue by JCorson** [enthought/traitsui#257]
Tested on OSX 10.11 with wxpython 3.0.2.0-1 and traitsui 5.0.0-1.
The program works with qt4 as the backend, but crashes using wx returning this traceback repeated numerous times. 

```
Exception occurred in traits notification handler for object: <__main__.ListEditorDemo object at 0x10d7a6c50>, trait: play_list, old value: ['The Merchant of Venice', 'Hamlet', 'MacBeth'], new value: ['Hamlet', 'The Merchant of Venice', 'MacBeth']
Traceback (most recent call last):
  File "/Users/jcorson/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/jcorson/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 615, in dispatch
    handler( *args )
  File "/Users/jcorson/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/editor.py", line 366, in _update_editor
    self.update_editor()
  File "/Users/jcorson/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/wx/list_editor.py", line 181, in update_editor
    list_pane.DestroyChildren()
  File "/Users/jcorson/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/wx/_core.py", line 9191, in DestroyChildren
    return _core_.Window_DestroyChildren(*args, **kwargs)
PyAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/vagrant/pisi-64bit/tmp/wxPython-3.0.2.0-1/work/wxPython-src-3.0.2.0/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
```

A warning also appears with the following message:

```
-c Warning
iccp: known incorrect sRGB profile
```

CC: @RobinD42

**Comment by JCorson** [comment]
xref: https://enthought.zendesk.com/agent/tickets/59445

**Comment by RobinD42** [comment]
The iccp warning is due to newer libpng versions being more strict about the contents of PNG image files, and will likely be fixed by updating the icon image file used in that example.

http://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

**Comment by RobinD42** [comment]
The fix for the exception will likely be similar to #108 and/or #153

**Comment by corranwebster** [comment]
I think that https://github.com/enthought/pyface/pull/184 fixes the issue with the main crash.

**Comment by JCorson** [comment]
@corranwebster. I tested enthought/pyface#184 by installing pyface from master into a venv. The main crash still happens with wx as the backend. Did I miss a step to test this properly?

**Comment by corranwebster** [comment]
No, that should have been enough.  I am not seeing the crash on my machine - same wxpython, but master of traits, for whatever its worth (that shouldn't affect things), on OS X Yosemite.

I'll look into it some more.

**Comment by JCorson** [comment]
Not sure if it makes a difference, but I am running OSX 10.11 and ran `export ETS_TOOLKIT=wx` before  running `python ListEditor_demo.py`

**Comment by corranwebster** [comment]
I am not seeing this on current master in a clean EDM environment.  I am going to close this.
